apiVersion: v1
kind: Namespace
metadata:
  name: nginx2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2-deployment
  namespace: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx2-service
  namespace: nginx2
spec:
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx2-ingress
  namespace: nginx2
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod-wildcard"
spec:
  tls:
    - hosts:
        - "*.sutty.shop"
      secretName: letsencrypt-prod-wildcard
  rules:
    - host: test2.sutty.shop
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx-service
                port:
                  number: 80