apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-prod-cert
  namespace: cert-manager
spec:
  secretName: wildcard-prod-cert-tls
  issuerRef:
    name: letsencrypt-prod-wildcard
    kind: ClusterIssuer
  dnsNames:
    - 'sutty.shop'
    - '*.sutty.shop'
